name: seekhobuddy
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  flutter_cached_pdfview: ^0.4.2
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.1
  firebase_storage: ^11.7.7
  multi_select_flutter: ^4.0.0
  firebase_database: ^10.5.7
  flutter_image_compress: ^1.1.0
  url_launcher: ^6.2.6
  webview_flutter: ^2.0.13
  file_picker: ^8.0.3
  firebase_messaging: ^14.9.4
  googleapis_auth: ^1.6.0
  googleapis: ^13.1.0
  flutter_local_notifications: ^9.1.2
  path_provider: ^2.0.8
  flutter_launcher_icons: ^0.13.1
  onesignal_flutter: ^3.2.6
  flutter_gemini_bot: ^0.0.4
  google_generative_ai: ^0.4.3
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "seekhobuddy.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSans3-VariableFont_wght.ttf
    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf
